# Generated by Django 3.1.1 on 2020-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url_links',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('links', models.CharField(max_length=10000000000)),
                ('short_link', models.CharField(max_length=100000)),
            ],
        ),
    ]
